# Generated by Django 5.2.8 on 2025-11-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=16)),
                ('temp_inside_c', models.FloatField()),
                ('setpoint_c', models.FloatField()),
                ('temp_outside_c', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('device_ts', models.DateTimeField(blank=True, null=True)),
                ('server_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'server_ts'], name='api_telemet_device__746848_idx')],
            },
        ),
    ]
