# Generated by Django 5.2.8 on 2025-11-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='hysteresis_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='output',
            field=models.CharField(blank=True, help_text='Current actuator output state', max_length=16),
        ),
    ]
