# Generated by Django 5.2.8 on 2025-12-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_last_seen_alter_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_enabled', models.BooleanField(default=False)),
                ('high_temp_enabled', models.BooleanField(default=False)),
                ('high_temp_threshold', models.FloatField(default=30.0)),
                ('low_temp_enabled', models.BooleanField(default=False)),
                ('low_temp_threshold', models.FloatField(default=10.0)),
                ('min_alert_interval_minutes', models.IntegerField(default=30)),
                ('last_high_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('last_low_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('custom_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='api.device')),
            ],
            options={
                'verbose_name': 'Device Alert Settings',
                'verbose_name_plural': 'Device Alert Settings',
            },
        ),
    ]
