# Generated by Django 5.2.8 on 2025-12-05 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devicealertsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free (2 GB)'), ('standard', 'Standard (10 GB)'), ('premium', 'Premium (1 TB)')], default='free', max_length=20)),
                ('cached_usage_bytes', models.BigIntegerField(default=0)),
                ('usage_last_calculated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Storage Profile',
                'verbose_name_plural': 'User Storage Profiles',
            },
        ),
    ]
